### ISSUE TITLE
syntax error when trying to open the UI

### ISSUE THREAD

**Issue by KopiPandan** [RedForty/Animation-Pin-Tool#1]
Hi Daniel! Hope you are doing well! I'm a former student of yours from Animsquad course a few years ago and I have been using your tool since I took your class! Recently, I re-installed maya and I've been trying to install the tool to maya 2022, but it keeps giving me this error for some reason...

# Error: invalid syntax # 
import animPin as animPin
animPin.show()
```
# Error: invalid syntax # 

I was wondering if you might know what is the issue. I put the two scripts under here: C:\Program Files\Autodesk\Maya2022\scripts
if this info helps! Thank you so much! :)

**Comment by RedForty** [comment]
Hey there! Thank you for the feedback! Hrmm... I think the problem is Maya 2022 and the upgrade to python 3. I'll dig into this to see about fixing the issues.

**Comment by KopiPandan** [comment]
Yayyy! Thank you, Daniel! I love this tool so much, it's such a lifesaver!

**Comment by RedForty** [comment]
Fixed! Pull latest and give it a try!

**Comment by KopiPandan** [comment]
Yay! I'll give it a try! Thank you so much!!
